server:
  servlet:
    context-path: /exam
  port: 8880
spring:
  cache:
    type: redis

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/ph_exam?characterEncoding=utf8&useSSL=false&serverTimezone=CTT&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root1234

  redis:
    database: 0
    host: localhost
    port: 6379


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  typeAliasesPackage: com.ph.exam.mapper
  mapperLocations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-handlers-package: com.ph.exam.typeHandler